type GeoLoc{
    latitude: Float!
    longitude: Float!
}

type Airport{
    name: String!
    city: String!
    country: String!
    iata_code: String!
    geoloc: GeoLoc!
    links_count: Int
    objectID: String
}

extend type Query{
    getAllAirports: String
    getAirportById(Id: String): String
}