type Response{
    message: String!
    status: String!
    method: String!
}

type AuthResponse{
    message: String!
    accessToken: String!
}

type TripResonse{
    message: String!
    tId: String!
}