type Trip{
    tId: String!
    userid: String!
    fId: String!
    mealOption: String!
    class: String!
    seatNo: String!
}

extend type Query{
    getAllTrips: String!
    getUserTrips(userid: String!): String!
    getTripById(ID: String!): String!
}