type User{
    uId: String!
    name: String!
    email: String!
    phone: String!
    password: String!
    balance: Int!
    isActive: Int!
    home: String!
    currentLocation: String!
}

extend type Query{
    getUserById(ID: String!): User!
    getAllUsers: [User!]!
}